# ~/registry/docker-compose.yml
version: "3.8"
services:
  registry:
    image: registry:2
    container_name: local-registry
    ports:
      - "5000:5000"
    restart: unless-stopped
    environment:
      REGISTRY_STORAGE_DELETE_ENABLED: "true"
    volumes:
      - ./data:/var/lib/registry