slug: subdomains_enum
version: "1"
description: "Enumerate subdomains under owned roots using the subdomain-synth tool profile, batched for safety."
labels:
  category: recon
  stability: stable

steps:
  - name: "Enumerate subdomains"
    profile:
      slug: subdomain-synth-default      # profile that binds tool: subdomain-synth@0.1.0 (or similar)
      version: "1"
    scope_rule:
      slug: domains_prod            # scope rule that selects production domains (InvDomain)
      version: "1"
    batch:
      max_targets: 1             # how many inventory items (roots/targets) per batch
      max_concurrency: 5            # how many jobs the launcher can run in parallel
