schemaVersion: asm/v1
kind: Playbook
metadata:
  slug: test_playbook_simple
  version: "1"
  name: "test_playbook_simple"

bindings:
  - idx: 0
    alias: dns-passive
    task: dns.passive@1
    scopeMap:
      InvDomain: tenant_root_domains@1
    promotionRuleset: tenant_root_domains@1
    overrides:
      tool:
        params:
          resolveA: true
          resolveAAAA: true
          emitMode: "domains+records"
      coverage:
        ttlByAnchor:
          InvDomain: 7d
        variant: domain