schemaVersion: asm/v1
kind: Playbook
metadata:
  slug: net-web-enum-passive-altmut-scan-httpx
  version: "1.0.0"
  name: "DNS Passive + AltMutations + Port Scan + HTTPX"

bindings:
  - idx: 0
    alias: dns-passive
    task: dns.passive@1
    scopeMap:
      InvDomain: tenant_root_domains@1
    promotionRuleset: tenant_root_domains@1
    overrides:
      tool:
        params:
          resolveA: true
          resolveAAAA: true
          emitMode: "domains+records"
      coverage:
        ttlByAnchor:
          InvDomain: 7d
        variant: domain

  - idx: 1
    alias: dns-altmutation
    task: dns.altmutation@1
    scopeMap:
      InvDomain: tenant_root_domains@1
    context:
      tenantKnownSubdomains:
        kind: InvDnsRecord
        ruleset: tenant_dns_all@1
    promotionRuleset: tenant_root_domains@1
    overrides:
      tool:
        params:
          useCommonPrefixes: true
          useTenantPrefixes: true
          maxCandidatesPerBase: 5000
          resolveA: true
          resolveAAAA: true
      coverage:
        ttlByAnchor:
          InvDomain: 7d
        variant: domain

  - idx: 2
    alias: tcp-scan
    task: masscan.tcp_scan@1
    scopeMap:
      InvIP: dns_resolved_ips_recent@1
    promotionRuleset: promotion_ip_all@1
    overrides:
      tool:
        params:
          ports: "80,443"
          scanRate: "auto"
      coverage:
        ttlByAnchor:
          InvIP: 7d            # was InvIPAddress
        variant: ip
      constraints:
        maxBatchSize: 254       # was max_targets
        maxConcurrency: 5       # was max_concurrency

  - idx: 3
    alias: httpx-hostport
    task: httpx.hostport@1
    scopeMap:
      InvNetworkService: tcp_open_ports_recent@1
      InvDnsRecord: dns_recent@1
      InvHTTPService: http_service_recent@1   # consider this instead of InvDnsHTTPService
    promotionRuleset: promotion_http_services_all@1
    overrides:
      materialize:
        includeBareIpIfAliasesPresent: false
      coverage:
        ttlByAnchor:
          InvNetworkService: 7d
          InvHTTPService: 7d
        variant: derived
      tool:
        params:
          followRedirects: true
      constraints:
        maxBatchSize: 50
        maxConcurrency: 10
